# Generated by Django 4.2 on 2025-06-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
        ("users", "0003_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrators",
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="special_id",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
    ]
