# Generated by Django 4.2 on 2025-06-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
        ("leads", "0002_alter_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_clinic",
                to="clinic.clinic",
            ),
        ),
    ]
