# Generated by Django 4.2 on 2025-06-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
