# Generated by Django 4.2 on 2025-06-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office_assistant", "0002_officeassistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeassistant",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
