# Generated by Django 4.2 on 2025-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        ("doctor", "0001_initial"),
        ("leads", "0002_alter_lead_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "annual_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True, related_name="clinics", to="doctor.doctor"
                    ),
                ),
                (
                    "leads",
                    models.ManyToManyField(
                        blank=True, related_name="clinics", to="leads.lead"
                    ),
                ),
                (
                    "patients",
                    models.ManyToManyField(
                        blank=True, related_name="clinics", to="patient.patient"
                    ),
                ),
            ],
        ),
    ]
