# Generated by Django 5.2.1 on 2025-05-21 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("name_pt", models.CharField(max_length=100, verbose_name="PT Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("description_pt", models.TextField(verbose_name="PT Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure",
                "verbose_name_plural": "Procedures",
            },
        ),
        migrations.CreateModel(
            name="CustomSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure",
                    models.CharField(max_length=50, verbose_name="Procedure"),
                ),
                ("date", models.CharField(max_length=20, verbose_name="Date")),
                ("time", models.CharField(max_length=20, verbose_name="Time")),
                ("details", models.TextField(verbose_name="Details")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent at"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Is confirmed"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Appointment",
                "verbose_name_plural": "Custom Appointments",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Scheduled at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is completed"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Is confirmed"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Time")),
                (
                    "confirmation_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Confirmation token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schedule.procedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "unique_together": {("date", "time")},
            },
        ),
    ]
