# Generated by Django 4.2 on 2025-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_appointment_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Last Name"
            ),
        ),
    ]
