# Generated by Django 4.2 on 2025-06-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_doctor_clinic"),
        ("clinic", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_clinic",
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="doctor.doctor",
            ),
        ),
    ]
