# Generated by Django 4.2 on 2025-06-14 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_password_doctor_profile_photo_doctor_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0004_appointment_appointmentphoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("policy_number", models.CharField(max_length=50)),
                ("coverage_details", models.TextField()),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Credit/Debit Card"),
                            ("insurance", "Insurance"),
                            ("transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                ("instructions", models.TextField()),
                ("prescribed_date", models.DateField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "insurance_coverage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "patient_responsibility",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="doctor.doctor",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date", "-time"]},
        ),
        migrations.AlterModelOptions(
            name="patientnote",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="patient",
            name="clinic",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="status",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_appointments",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.IntegerField(default=30, help_text="Duration in minutes"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="appointmentphoto",
            name="caption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="primary_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_patients",
                to="doctor.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patientnote",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_notes",
                to="patient.appointment",
            ),
        ),
        migrations.DeleteModel(
            name="PatientTreatmentPhoto",
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_plans",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="patient.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="patient.appointment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="treatment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="patient.treatmentplan",
            ),
        ),
        migrations.AddField(
            model_name="insurance",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_info",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="treatment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="patient.treatmentplan",
            ),
        ),
    ]
