# Generated by Django 4.2 on 2025-06-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
        ("patient", "0005_insurance_payment_prescription_treatmentplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_set",
                to="clinic.clinic",
            ),
        ),
    ]
