# Generated by Django 4.2 on 2025-06-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0006_patient_clinic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
    ]
