# Generated by Django 4.2 on 2025-05-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("GD", "General Dentist"),
                            ("OR", "Orthodontist"),
                            ("PE", "Periodontist"),
                            ("EN", "Endodontist"),
                            ("OS", "Oral Surgeon"),
                            ("PD", "Pediatric Dentist"),
                            ("PR", "Prosthodontist"),
                        ],
                        default="GD",
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
