# Generated by Django 4.2 on 2025-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_password_doctor_profile_photo_doctor_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_active",
        ),
    ]
